name: Terraform Plan

on:
  push:
    branches:
      - feature/iac-pipeline-setup
  # pull_request:
  #   branches:
  #     - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Pure Job ke liye ek hi baar Environment Variables set kar diye hain
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.15.8

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Terraform Format
    #   run: terraform fmt 
    #   working-directory: env

    - name: Terraform Init
      run: terraform init
      working-directory: env/preprod

    - name: Terraform Validate
      run: terraform validate
      working-directory: env/preprod

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: env/preprod