name: Terraform Plan

on:
  push:
    branches:
      - feature/iac-pipeline-setup
  # pull_request:
  #   branches:
  #     - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.15.8

    # - name: Azure Login (via Action)
    #   uses: azure/login@v3

    - name: Azure Login 
      run: |
        az login \
          --service-principal \
          --username "${{ secrets.ARM_CLIENT_ID }}" \
          --password "${{ secrets.ARM_CLIENT_SECRET }}" \
          --tenant "${{ secrets.ARM_TENANT_ID }}"

    - name: Set Azure Subscription
      run: |
        az account set \
          --subscription "${{ secrets.ARM_SUBSCRIPTION_ID }}"

    - name: Check Azure Login
      run: az account show

    - name: Terraform Init
      run: terraform init
      working-directory: env/preprod

    - name: Terraform Validate
      run: terraform validate
      working-directory: env/preprod

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: env/preprod
